services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  customer_service:
    build: ./backend/customer_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/customers
    depends_on:
      - postgres
    ports:
      - "8001:8000"

  order_service:
    build: ./backend/order_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/orders
    depends_on:
      - postgres
    ports:
      - "8002:8000"

  product_service:
    build: ./backend/product_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/products
    depends_on:
      - postgres
    ports:
      - "8003:8000"

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - customer_service
      - order_service
      - product_service
