apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: sit722acrishita.azurecr.io/task10_2d-order-service:latest
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/orders
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: 8002
      targetPort: 8002
