apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium   # AKS default storage
  resources:
    requests:
      storage: 1Gi
