name: CI Pipeline

on:
  push:
    branches: [ "testing", "main" ]
  pull_request:
    branches: [ "testing", "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r backend/customer_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install -r backend/product_service/requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for postgres..."
            sleep 3
          done

      - name: Create test databases
        run: |
          psql -h localhost -U postgres -c "CREATE DATABASE customers;"
          psql -h localhost -U postgres -c "CREATE DATABASE orders;"
          psql -h localhost -U postgres -c "CREATE DATABASE products;"

      - name: Run Customer Service tests
        run: pytest backend/customer_service/tests

      - name: Run Order Service tests
        run: pytest backend/order_service/tests

      - name: Run Product Service tests
        run: pytest backend/product_service/tests
