name: CI Pipeline

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies (Customer Service)
        run: |
          pip install -r backend/customer_service/requirements.txt
          pip install pytest

      - name: Install dependencies (Order Service)
        run: |
          pip install -r backend/order_service/requirements.txt
          pip install pytest

      - name: Install dependencies (Product Service)
        run: |
          pip install -r backend/product_service/requirements.txt
          pip install pytest

      - name: Ensure test databases exist
        run: |
          sudo apt-get install -y postgresql-client
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'customers'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE customers"
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'orders'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE orders"
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'products'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE products"
        env:
          PGPASSWORD: postgres

      - name: Run Customer Service tests
        run: pytest backend/customer_service/tests

      - name: Run Order Service tests
        run: pytest backend/order_service/tests

      - name: Run Product Service tests
        run: pytest backend/product_service/tests
