name: CI Pipeline

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Install deps & run tests for each service
      - name: Install dependencies & run tests (Customer Service)
        run: |
          pip install -r backend/customer_service/requirements.txt
          pytest backend/customer_service/tests

      - name: Install dependencies & run tests (Order Service)
        run: |
          pip install -r backend/order_service/requirements.txt
          pytest backend/order_service/tests

      - name: Install dependencies & run tests (Product Service)
        run: |
          pip install -r backend/product_service/requirements.txt
          pytest backend/product_service/tests

      # Ensure DBs exist for tests
      - name: Ensure test databases exist
        run: |
          sudo apt-get install -y postgresql-client
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'customers'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE customers"
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'orders'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE orders"
          psql -h localhost -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'products'" | grep -q 1 || psql -h localhost -U postgres -c "CREATE DATABASE products"
        env:
          PGPASSWORD: postgres

      # Login to Azure using GitHub secret
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login to ACR
      - name: Azure Container Registry Login
        run: |
          az acr login --name sit722acr09ishita2505

      # Build & push images
      - name: Build and Push Docker Images
        run: |
          docker build -t sit722acr09ishita2505.azurecr.io/customer-service:latest backend/customer_service
          docker push sit722acr09ishita2505.azurecr.io/customer-service:latest

          docker build -t sit722acr09ishita2505.azurecr.io/order-service:latest backend/order_service
          docker push sit722acr09ishita2505.azurecr.io/order-service:latest

          docker build -t sit722acr09ishita2505.azurecr.io/product-service:latest backend/product_service
          docker push sit722acr09ishita2505.azurecr.io/product-service:latest
