name: CI

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main", "testing" ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: customers   # default DB for startup
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r backend/customer_service/requirements.txt
        pip install -r backend/order_service/requirements.txt
        pip install -r backend/product_service/requirements.txt
        pip install pytest

    - name: Create test databases
      run: |
        sudo apt-get install -y postgresql-client
        # Create missing DBs for all services
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE DATABASE customers;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE DATABASE orders;"
        PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -c "CREATE DATABASE products;"

    - name: Run Customer Service tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/customers
      run: pytest backend/customer_service/tests

    - name: Run Order Service tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/orders
      run: pytest backend/order_service/tests

    - name: Run Product Service tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/products
      run: pytest backend/product_service/tests
