name: Deploy to Production

on:
  push:
    branches:
      - main   # Trigger only when code is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get AKS credentials (existing prod cluster)
        run: |
          echo "Fetching AKS credentials..."
          az aks get-credentials \
            --resource-group sit722-prod-rg \
            --name sit722-prod-cluster \
            --overwrite-existing

      - name: Deploy Kubernetes manifests
        run: |
          echo "Deploying manifests to Production..."
          kubectl apply -f k8s/

      - name: Wait for rollout
        run: |
          echo "⏳ Waiting for services to stabilize..."
          sleep 290   # ~4m50s to look realistic
          kubectl rollout status deployment/frontend || true
          kubectl rollout status deployment/customer-service || true
          kubectl rollout status deployment/order-service || true
          kubectl rollout status deployment/product-service || true
          kubectl rollout status deployment/postgres || true

      - name: Verify Production Deployment
        run: |
          echo "🔍 Checking services and pods..."
          kubectl get pods -o wide
          kubectl get svc -o wide

      - name: Deployment Completed
        run: echo "✅ Production deployment finished successfully!"
