name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group sit722-prod-rg \
            --name sit722-prod-cluster \
            --overwrite-existing

      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/
          kubectl get pods -o wide
          kubectl get svc -o wide
