name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials (ignore missing RG)
        run: |
          az aks get-credentials \
            --resource-group sit722-prod-rg \
            --name sit722-prod-cluster \
            --overwrite-existing || echo "Skipping prod deploy (RG/Cluster not found)"

      - name: Deploy manifests to AKS (ignore if cluster missing)
        run: |
          kubectl apply -f k8s/ || echo "Skipping prod apply (no cluster)"
