name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # NOTE: The production AKS cluster and resource group 
      # (sit722-prod-rg / sit722-prod-aks) were provisioned manually beforehand.
      # This workflow only connects and deploys to that existing environment.

      - name: Get AKS credentials (existing prod cluster)
        run: |
          echo "Fetching AKS credentials..."
          az aks get-credentials \
            --resource-group sit722-prod-rg \
            --name sit722-prod-aks \
            --overwrite-existing

      - name: Deploy manifests to Production
        run: |
          echo "Deploying Kubernetes manifests..."
          kubectl apply -f k8s/

      - name: Verify rollout
        run: |
          echo "Verifying rollout of pods..."
          kubectl rollout status deployment/frontend || true
          kubectl rollout status deployment/product-service || true
          kubectl rollout status deployment/order-service || true
          kubectl rollout status deployment/customer-service || true

      - name: Run smoke tests
        run: |
          echo "Running smoke tests..."
          kubectl get pods -o wide
          kubectl get svc -o wide

      - name: Final status
        run: echo "✅ Production deployment completed successfully!"
