name: deploy-prod

on:
  push:
    branches:
      - main   # Trigger production deployment when code is merged into main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up job
        run: echo "Starting production deployment..."

      - name: Pre Log in to Azure
        run: echo "Preparing Azure login..."

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group sit722-prod-rg \
            --name sit722-prod-cluster \
            --overwrite-existing

      - name: Deploy Kubernetes manifests
        run: |
          echo "Deploying Kubernetes manifests..."
          kubectl apply -f k8s/

      - name: Wait for rollout
        run: |
          echo "Checking rollout status..."
          kubectl rollout status deployment/frontend-deployment --timeout=300s
          kubectl rollout status deployment/order-service --timeout=300s
          kubectl rollout status deployment/product-service --timeout=300s
          kubectl rollout status deployment/customer-service --timeout=300s

      - name: Verify Production Deployment
        run: |
          echo "Running smoke tests against production..."
          kubectl get pods -o wide
          kubectl get svc
          kubectl get deployments

      - name: Deployment Completed
        run: echo "✅ Production deployment completed successfully!"

      - name: Post Checkout repository
        run: echo "Repository checkout complete."

      - name: Post Log in to Azure
        run: echo "Azure session closed."

      - name: Complete job
        run: echo "Production deployment pipeline finished."
