name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------------- BUILD & PUSH TO ACR ----------------
      - name: Build and Push Docker images
        run: |
          az acr build --registry sit722acrishita \
                       --image myapp:${{ github.sha }} .

      # ---------------- DEPLOY TO EXISTING PROD ----------------
      - name: Get AKS credentials
        run: az aks get-credentials -g sit722-prod-rg -n sit722-prod-cluster --overwrite-existing || echo "Prod cluster not found, skipping..."

      - name: Deploy manifests
        run: kubectl apply -f k8s/ || echo "Skipping deploy since prod cluster is missing"
