name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upgrade Azure CLI
        run: |
          sudo az upgrade --yes

      - name: Create resource group
        run: |
          az group create \
            --name sit722-staging-rg \
            --location australiaeast

      - name: Create AKS cluster
        run: |
          az aks create \
            --resource-group sit722-staging-rg \
            --name sit722-staging-cluster \
            --node-count 1 \
            --node-vm-size Standard_B2s \
            --enable-managed-identity \
            --generate-ssh-keys

      - name: Attach ACR to AKS
        run: |
          az aks update \
            --resource-group sit722-staging-rg \
            --name sit722-staging-cluster \
            --attach-acr sit722acrishita

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group sit722-staging-rg \
            --name sit722-staging-cluster

      - name: Deploy Kubernetes manifests
        run: |
          kubectl apply -f task10_2d/k8s/
