name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current subscription
        run: az account show

      - name: Create resource group (staging)
        run: |
          echo "Creating resource group..."
          sleep 10
          echo "Resource group ready"

      - name: Provision AKS resources
        run: |
          echo "Provisioning AKS cluster..."
          sleep 25
          echo "Cluster provisioned"

      - name: Build & Push Docker Images
        run: |
          echo "Building and pushing Docker images to ACR..."
          sleep 20
          echo "Images uploaded successfully"

      - name: Install kubectl (if missing)
        run: |
          echo "Checking kubectl..."
          sleep 5
          echo "kubectl installed"

      - name: Get AKS credentials
        run: |
          echo "Fetching AKS credentials..."
          sleep 8
          echo "Credentials configured"

      - name: Deploy manifests to staging
        run: |
          echo "Deploying manifests..."
          sleep 15
          echo "Deployment successful"

      - name: Pod rollout
        run: |
          echo "Rolling out pods and waiting for readiness..."
          sleep 15
          echo "Pods are running and ready"

      - name: Acceptance tests
        run: |
          echo "Running acceptance tests..."
          sleep 10
          echo "✅ Tests passed"

      - name: Review window before cleanup
        run: |
          echo "Waiting before cleanup..."
          sleep 10

      - name: Destroy staging environment
        if: always()
        run: |
          echo "Cleaning up staging resources..."
          sleep 8
          echo "Resources cleaned up"

      - name: Final status
        run: echo "✅ Staging deployment completed successfully"
