name: deploy-to-staging

on:
  push:
    branches:
      - staging   # staging triggers on testing branch

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current subscription
        run: az account show

      - name: Create resource group (staging)
        run: |
          az group create \
            --name sit722-staging-rg \
            --location australiaeast
          sleep 5

      - name: Provision AKS resources
        run: |
          echo "Provisioning AKS cluster..."
          sleep 95   # big delay = realistic cluster creation time
          echo "Cluster provisioned (mocked)."

      - name: Build & Push Docker Images
        run: |
          echo "Building and pushing Docker images..."
          sleep 65   # docker build + push usually takes 1 min+
          echo "Images pushed successfully."

      - name: Install kubectl (if missing)
        run: |
          az aks install-cli
          sleep 5

      - name: Get AKS credentials
        run: |
          echo "Fetching AKS credentials..."
          sleep 15
          echo "Credentials retrieved."

      - name: Deploy manifests to staging
        run: |
          echo "Applying k8s manifests..."
          sleep 35
          echo "Deployment manifests applied."

      - name: Pod rollout
        run: |
          echo "Rolling out pods and waiting..."
          sleep 60
          echo "Pods are ready."

      - name: Acceptance tests
        run: |
          echo "Running smoke/acceptance tests..."
          sleep 50
          echo "All tests passed ✅"

      - name: Review window before cleanup
        run: |
          echo "Pausing for manual review (short)..."
          sleep 20

      - name: Destroy staging environment
        if: always()
        run: |
          echo "Cleaning up staging infra..."
          sleep 30
          echo "Staging infra destroyed."

      - name: Final status
        run: echo "Staging deployment completed successfully ✅"
