name: Deploy to Staging

on:
  push:
    branches:
      - staging   # Trigger when code is pushed to the stagingbranch

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show current subscription
        run: az account show

      - name: Create resource group (staging)
        run: |
          az group create \
            --name sit722-staging-rg \
            --location australiaeast

      - name: Provision AKS resources
        run: |
          az aks create \
            --resource-group sit722-staging-rg \
            --name sit722-staging-aks \
            --node-count 1 \
            --generate-ssh-keys

      - name: Build & Push Docker Images
        run: |
          az acr build \
            --registry sit722acrishita2505 \
            --resource-group sit722-rg \
            --image frontend:staging ./frontend
          
          az acr build \
            --registry sit722acrishita2505 \
            --resource-group sit722-rg \
            --image backend:staging ./backend

      - name: Install kubectl (if missing)
        run: az aks install-cli

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group sit722-staging-rg \
            --name sit722-staging-aks \
            --overwrite-existing

      - name: Deploy manifests to staging
        run: |
          kubectl apply -f task10_2d/k8s/

      - name: Simulate pod rollout
        run: kubectl rollout status deployment/frontend --timeout=60s || true

      - name: Acceptance tests (simple smoke)
        run: |
          echo "Running smoke tests..."
          kubectl get pods
          kubectl get svc

      - name: Wait before destroying staging (human review window)
        run: sleep 60

      - name: Destroy staging environment (always)
        if: always()
        run: |
          az group delete \
            --name sit722-staging-rg \
            --yes \
            --no-wait

      - name: Final status
        run: echo "✅ Staging pipeline completed successfully"
