name: Deploy to Staging

on:
  push:
    branches:
      - testing

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ---------------- TEST STAGE ----------------
      - name: Run Unit Tests
        run: |
          echo "Running tests..."
          # Replace with your test framework
          echo "All tests passed!"

      # ---------------- BUILD & PUSH TO ACR ----------------
      - name: Build and Push Docker images
        run: |
          az acr build --registry sit722acrishita \
                       --image myapp:${{ github.sha }} .

      # ---------------- CREATE TEMP STAGING ----------------
      - name: Create Resource Group
        run: az group create -n sit722-staging-rg -l australiaeast

      - name: Create AKS Cluster
        run: |
          az aks create -g sit722-staging-rg -n sit722-staging-cluster \
            --node-count 1 \
            --enable-managed-identity \
            --attach-acr sit722acrishita \
            --generate-ssh-keys \
            --node-vm-size Standard_B2s

      - name: Get AKS credentials
        run: az aks get-credentials -g sit722-staging-rg -n sit722-staging-cluster --overwrite-existing

      - name: Deploy manifests
        run: kubectl apply -f k8s/

      # ---------------- CLEANUP ----------------
      - name: Destroy Staging Environment
        if: always()
        run: az group delete -n sit722-staging-rg --yes --no-wait
